const { app, BrowserWindow, session } = require('electron')
const path = require('node:path')
const { registerDesktopAssets, resolveAssetPath } = require('../electron/desktopAssets.cjs')
const assert = require('node:assert/strict')
app.setPath('userData', path.resolve(__dirname, '../.test-desktop-profile'))
app.whenReady().then(async () => {
  const target = session.fromPartition('persist:origin-test')
  await registerDesktopAssets(target, path.resolve(__dirname, '../dist'))
  const originalFetch = target.fetch.bind(target)
  target.fetch = async () => { throw new Error('Sin internet en la prueba') }
  const window = new BrowserWindow({ show: false, webPreferences: { session: target, contextIsolation: true, nodeIntegration: false, sandbox: true, preload: path.resolve(__dirname, '../electron/preload.cjs') } })
  await window.loadURL('https://vape-pos.store/')
  const result = await window.webContents.executeJavaScript(`new Promise((resolve,reject)=>{const deadline=Date.now()+10000;const check=()=>{if(document.body.innerText.includes('Iniciar Sesion'))return resolve({url:location.href,text:document.body.innerText,desktop:window.vapePosDesktop?.isDesktop});if(Date.now()>deadline)return reject(new Error(document.body.innerText));setTimeout(check,100)};check()})`)
  assert.equal(result.url, 'https://vape-pos.store/')
  assert.equal(result.desktop, true)
  assert.match(result.text, /Entrar al Sistema/)
  assert.throws(() => resolveAssetPath(path.resolve(__dirname, '../dist'), '/..%5Cprivate.txt'))
  const missing = await originalFetch('https://vape-pos.store/assets/not-found.js')
  assert.equal(missing.status, 404)
  console.log('PASS desktop-origin: la aplicación empaquetada abre sin internet conservando el origen HTTPS, sin desactivar App Check; archivos inexistentes y rutas externas rechazados.')
  window.destroy()
  app.quit()
}).catch(error => { console.error(error); app.exit(1) })
